import { ContentItem, Fields, IContentItem } from 'kentico-cloud-delivery-typescript-sdk/_bundles';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' module.
 * You can substitute instances of 'IContentItem' with a model defined in other class
 * to get access to all properties. This is applicable only if you know what item type the field contains.
 */
export class Event extends ContentItem {
    public picturesFromPreviousYears: Fields.AssetsField;
    public openingDaysInAYearFrom: Fields.TextField;
    public description: Fields.RichTextField;
    public poiGroupPointsOfInterest: IContentItem[];
    public urlSlug: Fields.UrlSlugField;
    public poiGroupTitle: Fields.TextField;
    public openingDaysInAYearUntil: Fields.TextField;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {

                if (fieldName === 'pictures_from_previous_years') {
                    return 'picturesFromPreviousYears';
                }

                if (fieldName === 'opening_days__in_a_year___from') {
                    return 'openingDaysInAYearFrom';
                }

                if (fieldName === 'poi_group__points_of_interest') {
                    return 'poiGroupPointsOfInterest';
                }

                if (fieldName === 'url_slug') {
                    return 'urlSlug';
                }

                if (fieldName === 'poi_group__title') {
                    return 'poiGroupTitle';
                }

                if (fieldName === 'opening_days__in_a_year___until') {
                    return 'openingDaysInAYearUntil';
                }

                return fieldName;
            })
        });
    }
}
