import { ContentItem, Fields, IContentItem } from 'kentico-cloud-delivery-typescript-sdk';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' module.
 * You can substitute instances of 'IContentItem' with a model defined in other class
 * to get access to all properties. This is applicable only if you know what item type the field contains.
 */
export class PointOfInterest extends ContentItem {
    public urlSlug: Fields.UrlSlugField;
    public pictures: Fields.AssetsField;
    public description: Fields.RichTextField;
    public latitudeDecimalDegrees: Fields.NumberField;
    public longitudeDecimalDegrees: Fields.NumberField;
    public relatedPointsOfInterest: IContentItem[];
    public title: Fields.TextField;
    public elevationFt: Fields.NumberField;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {

                if (fieldName === 'url_slug') {
                    return 'urlSlug';
                }

                if (fieldName === 'latitude__decimal_degrees_') {
                    return 'latitudeDecimalDegrees';
                }

                if (fieldName === 'longitude__decimal_degrees_') {
                    return 'longitudeDecimalDegrees';
                }

                if (fieldName === 'related_points_of_interest') {
                    return 'relatedPointsOfInterest';
                }

                if (fieldName === 'elevation__ft_') {
                    return 'elevationFt';
                }

                return fieldName;
            })
        });
    }
}
