import { ContentItem, Fields, IContentItem } from 'kentico-cloud-delivery-typescript-sdk/_bundles';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' module.
 * You can substitute instances of 'IContentItem' with a model defined in other class
 * to get access to all properties. This is applicable only if you know what item type the field contains.
 */
export class Tour extends ContentItem {
    public images: Fields.AssetsField;
    public poiGroupPointsOfInterest: IContentItem[];
    public description: Fields.RichTextField;
    public poiGroupTitle: Fields.TextField;
    public tourType: Fields.MultipleChoiceField;
}