dist: trusty
language: node_js
sudo: required
node_js:
- "stable"
before_script:
- npm install
before_deploy:
- npm run build
deploy:
  provider: surge
  project: ./dist/
  domain: kentico-cloud-sample-pwa-app.surge.sh 
  skip_cleanup: true
