dist: trusty
language: node_js
sudo: required
addons:
    chrome: stable
node_js:
- "stable"
before_script:
- "sudo chown root /opt/google/chrome/chrome-sandbox"
- "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
- npm install
before_deploy:
- npm run build
deploy:
  provider: surge
  project: ./dist/
  domain: kentico-cloud-sample-pwa-app.surge.sh 
  skip_cleanup: true
