dist: trusty
language: node_js
node_js:
- "stable"
before_script:
- npm install
before_deploy:
- npm run build
deploy:
  provider: surge
  project: ./dist/
  domain: https://kentico-cloud-sample-pwa-app.surge.sh 
  skip_cleanup: true
after_deploy:
- npm run check-pwa-score
